#!/usr/bin/env perl
use strict;
use warnings;
use common::sense;
use utf8;
use feature ':5.20';
use warnings FATAL => qw{ uninitialized };
use autodie;

=pod

=head1 Title

  requestauthentication --- a server-based authenticator

=head1 Options

  requestauthentication user password

=head1 Description

  prints the original email if the authentication is correct.

=head1 Versions

  0.0: Thu May  4 06:45:00 2017

=cut

my @ok = qw( ivo.welch@syllabus.space iaw@syllabus.space ivo@syllabus.space );

print sub {
  @ARGV or return "we exist";
  ($ARGV[0]) or return "we exist";

  foreach (@ok) {
    (lc($_) eq lc($ARGV[0])) and return $ARGV[0];  ## correct
  }

  return "wrong user password ".join(" ", @ARGV);
} -> ();

